apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system

---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ longhorn.access_key_id | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ longhorn.secret_access_key | b64encode }}
  AWS_ENDPOINTS: {{ s3.url | b64encode }}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn-system
  version: v1.7.2
  valuesContent: |-
    service:
      ui:
        type: LoadBalancer

    persistence:
      reclaimPolicy: Retain
    defaultSettings:
      backupTarget: s3://{{ longhorn.bucket }}@{{ s3.region }}/backups
      backupTargetCredentialSecret: minio
      
      orphanAutoDeletion: false
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      nodeDrainPolicy: always-allow

---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-daily
  namespace: longhorn-system
spec:
  cron: "0 10 * * *"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 1