apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: prometheus
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus
  targetNamespace: prometheus
  valuesContent: |-
    commonMetaLabels:
      cluster: {{ cluster_context}}
    server:
      service:
        type: LoadBalancer
        servicePort: 9090
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "{{ cluster_context}}-prometheus"
      defaultFlagsOverride:
        - --storage.tsdb.retention.size=7GB
        - --config.file=/etc/config/prometheus.yml
    alertmanager:
      enabled: false
