all:
  vars:
    fiber: 00262586
    scrape: 120s
    arch: amd64
    cache_version: v0.5.3
    ticker_version: 3.10.7-beta.1
    extra_dst_args:
    pull: false
    dst_full: true
    clients: {}
    service_env: []
    ansible_user: riley
    latest_harness_delegate: 24.10.84104
    extra_packages:
      - git
      - zsh
      - mosh
      - rsync
  children:
    local:
      hosts:
        hurley:
          ansible_host: 192.168.2.2
          arch: arm64
        cornelius:
          ansible_host: 192.168.2.3
          rclone_opts: "-v copy /bucket/backup crypt:bucket/backup -L"
          rclone_utc_hour: 4
        charlie:
          ansible_host: 192.168.2.10
          full: false
          rclone_opts: "-v copy /mnt/bulk/k8s/frigate crypt:frigate -L"
          rclone_utc_hour: 6
          ceph_disk: /dev/sda
          cluster_name: lab
        jack:
          ansible_host: 192.168.2.11
          full: false
          ceph_disk: /dev/nvme0n1
        kate:
          ansible_host: 192.168.2.12
          full: false
          ceph_disk: /dev/nvme0n1
        claire:
          ansible_host: 192.168.2.13
          full: false
          ceph_disk: /dev/nvme0n1
    remote:
      hosts:
        # knapp:
        #   ansible_host: knapp.tail1e5ed.ts.net
        #   vars:
        #     docker_apt_arch: arm64
        #     docker_users:
        #     - riley
        #     - hunter
        zaius:
          ansible_host: 192.168.0.132
          cluster_name: urbandale
    oc:
      vars:
        ansible_user: ubuntu
        iptables: true
        arch: arm64
        extra_dst_args: -frequency=60 -redisAddress="oca0:6379"
        docker_apt_arch: arm64
        docker_users:
        - riley
        tailscale_args: "--reset"
      hosts:
        oca0:
          ansible_host: 129.146.149.166
          cluster_name: oc
        oca1:
          ansible_host: 129.153.217.210
        oca2:
          ansible_host: 158.101.27.222
        oca3:
          ansible_host: 144.24.58.138
        oca4:
          ansible_host: 129.153.95.143
          cluster_name: ocdr
        oca5:
          ansible_host: 129.146.157.81
        oca6:
          ansible_host: 144.24.63.75
        oca7:
          ansible_host: 129.146.43.216
        oca8:
          ansible_host: 129.153.144.225
        oca9:
          ansible_host: 129.158.255.22
        oca10:
          ansible_host: 129.158.237.210
        oca11:
          ansible_host: 129.158.243.254
