all:
  vars:
    fiber: 00262586
    scrape: 120s
    arch: amd64
    cache_version: v0.5.3
    ticker_version: 3.10.7-beta.1
    extra_dst_args:
    pull: false
    dst_full: true
    clients: {}
    service_env: []
    ansible_user: riley
    latest_harness_delegate: 24.10.84104
    extra_packages:
      - git
      - zsh
      - mosh
      - rsync
  children:
    local:
      hosts:
        hurley:
          ansible_host: 192.168.2.2
          arch: arm64
        zira:
          ansible_host: 192.168.2.6
        t480-0:
          ansible_host: 192.168.2.69
        plex: # t480-1
          ansible_host: 192.168.2.68
        ben:
          ansible_host: 192.168.2.65
        # charlie:
        #   ansible_host: 192.168.2.10
        #   full: false
        #   rclone_opts: "-v copy /mnt/bulk/k8s/frigate crypt:frigate -L"
        #   rclone_utc_hour: 6
        #   ceph_disk: /dev/sda
        #   cluster_context: lab
        jack:
          # ansible_host: 192.168.2.11
          full: false
          ceph_disk: /dev/nvme0n1
        claire:
          # ansible_host: 192.168.2.13
          full: false
          ceph_disk: /dev/nvme0n1
    remote:
      hosts:
        # knapp:
        #   ansible_host: knapp.tail1e5ed.ts.net
        #   vars:
        #     docker_apt_arch: arm64
        #     docker_users:
        #     - riley
        #     - hunter
        zaius:
          # ansible_host: 192.168.0.132
          cluster_context: urban
        sawyer:
          ansible_host: 192.168.2.3
    oc:
      vars:
        ansible_user: ubuntu
        iptables: true
        arch: arm64
        extra_dst_args: -frequency=60 -redisAddress="oca0:6379"
        docker_apt_arch: arm64
        docker_users:
        - riley
        tailscale_args: "--reset"
      hosts:
        oca0:
          ansible_host: 129.146.149.166
          cluster_context: oc
        oca1:
          ansible_host: 129.153.217.210
        oca2:
          ansible_host: 158.101.27.222
        oca3:
          ansible_host: 144.24.58.138
        oca8:
          ansible_host: 129.153.144.225
        oca9:
          ansible_host: 129.158.255.22
        oca10:
          ansible_host: 129.158.237.210
        oca11:
          ansible_host: 129.158.243.254
