all:
  vars:
    scrape: 120s
    arch: amd64
    ansible_user: riley
    host_key_checking: false
  ansible_ssh_extra_args0: '-o StrictHostKeyChecking=no'
  children:
    pve:
      hosts:
        home.r.ss:
          tailscale_args: --advertise-exit-node 
        prometheus.r.ss:
        emma.r.ss:
        bao.r.ss:
        cornelius.r.ss:
        plex.r.ss:
        polk.r.ss:
    local:
      hosts:
        hurley.r.ss:
          arch: arm64
        ben.r.ss:
        baelor.r.ss:
    remote:
      hosts:
        # knapp:
        #   ansible_host: knapp.tail1e5ed.ts.net
        #   vars:
        #     docker_apt_arch: arm64
        #     docker_users:
        #     - riley
        #     - hunter
        saywer:
    oc:
      vars:
        ansible_user: ubuntu
        iptables: true
        arch: arm64
        extra_dst_args: -frequency=60 -redisAddress="oca0:6379"
        docker_apt_arch: arm64
        docker_users:
        - riley
        tailscale_args: "--reset"
      hosts:
        oca0:
          # ansible_host: 129.146.149.166
          cluster_context: oc
        oca1:
          ansible_host: 129.153.217.210
        oca2:
          ansible_host: 158.101.27.222
        oca3:
          ansible_host: 144.24.58.138
        oca8:
          ansible_host: oca8.rileysnyder.dev
