all:
  vars:
    s3:
      host: https://axnsjajcck26.compat.objectstorage.us-phoenix-1.oraclecloud.com
      username: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        36396463343736666533343565313537393637666633396536333831333435366639653331396364
        6137303935356438363833303237646536323132393064340a633535383166336436303266646233
        38363731373563346331376435666363323061633730653337653530316231393261333033333939
        3833343038303637360a646362633937633232303866313765356437306165376631313638316130
        62663231623433653363613664316639316337646461643532353065323033313363346337636533
        3961643064653737666435386336333766396664643932373037
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        66373964333933663163383336663435363165663431376538363266633533633064666134333336
        6336363363353239323635376135386461306430316338630a326135613135313035343061616464
        32623336656439323265653439633233333432666431333237363366323637396135313261623733
        3534616666393137640a643063653835643362343533623232323265326266386232396432313961
        30353161646237353530353164613731626137303538313166643662646165353562646132373161
        3565326437383832613863333534343230333538353537336430
    scrape: 120s
    arch: linux-amd64
    cache_version: v0.4.0
    ticker_version: v3.7.2
    extra_dst_args:
    pull: false
    internal_net: 192.168.100.0/24
    iptables: false
    clients: {}
  children:
    local:
      hosts:
        kate:
          ansible_host: 192.168.0.61
          ansible_user: riley
        bigblackbox:
          ansible_host: 10.253.0.1
          ansible_user: root
    oracle:
      vars:
        ansible_user: ubuntu
        iptables: true
      hosts:
        oc0:
          ansible_host: 129.146.252.4
          dns_domain: cloud
          dns_entry: "*.cloud"
        oc1:
          ansible_host: 158.101.7.17
        oc2:
          ansible_host: 193.122.160.213
        oc7:
          ansible_host: 150.230.42.166
        oc8:
          ansible_host: 150.136.175.231
        oc9:
          ansible_host: 129.213.121.240
    oracle_dst:
      vars:
        ansible_user: ubuntu
        iptables: true
        extra_dst_args: -frequency=10
      hosts:
        oc3:
          ansible_host: 150.136.174.234
          scrape: 30s
          clients:
            biggi:
              name: biggi
              port: 8000
            kas:
              name: kas
              port: 8025
        oc4:
          ansible_host: 152.70.151.74
          scrape: 30s
          clients:
            emilevz: # Bull & Bear Crypto Discord Group
              name: emilevz
              port: 8000
              crypto: 44
        oc5:
          ansible_host: 132.226.31.70
          scrape: 30s
          clients:
            bluewaveaudio:
              name: bluewaveaudio
              port: 8000
        oc6:
          ansible_host: 152.67.251.170
          scrape: 30s
          clients:
            ender:
              name: ender
              port: 8000
    ocean:
      vars:
        ansible_user: root
        extra_dst_args: -redisAddress="10.108.0.9:6379"  -frequency=10
      hosts:
        cache:
          ansible_host: 159.65.175.81
        public:
          ansible_host: 138.197.14.249
          extra_dst_args: -redisAddress="10.108.0.9:6379" -frequency=90
          clients:
            public:
              name: public
              port: 8000
        do0:
          ansible_host: 142.93.178.78
          scrape: 30s
          clients:
            bugs:
              name: bugs
              port: 8000
            # hugodzilla:
            #   name: hugodzilla
            #   port: 8001
            caedosalt:
              name: caedos-alt
              port: 8001
            caedos:
              name: caedos
              port: 8002
            kingkong:
              name: kingkong
              port: 8003
            apexishunter:
              name: apexishunter
              port: 8004
            wil:
              name: wil
              port: 8005
            # cheeto:
            #   name: cheeto
            #   port: 8006
            # bitcoin:
            #   name: bitcoin
            #   port: 8007
            ami:
              name: ami
              port: 8008
            matt:
              name: matt
              port: 8009
            nine:
              name: nine
              port: 8010
            walterjazz:
              name: walterjazz
              port: 8011
            magsasaka:
              name: magsasaka
              port: 8012
            quantasy:
              name: quantasy
              port: 8013
            # sadi:
            #   name: sadi
            #   port: 8014
            # chia:
            #   name: chia
            #   port: 8015
            relax:
              name: relax
              port: 8016
            pyroborg:
              name: pyroborg
              port: 8017
            shimagunz:
              name: shimagunz
              port: 8018
            cibbers:
              name: cibbers
              port: 8019
            iwinoliver:
              name: iwinoliver
              port: 8020
            c4pt4in:
              name: c4pt4in
              port: 8021
            limi:
              name: limi
              port: 8022
            slapu:
              name: slapu
              port: 8025
            exus:
              name: exus
              port: 8026
            nicolepatt:
              name: nicolepatt
              port: 8027
            monroy:
              name: monroy
              port: 8028
            luffyowls:
              name: luffyowls
              port: 8029
            torpedo:
              name: torpedo
              port: 8030
            sinister:
              name: sinister
              port: 8031
        do1:
          ansible_host: 68.183.158.212
          scrape: 30s
          clients:
            magux:
              name: magux
              port: 8035
            doyalalexander:
              name: doyalalexander
              port: 8036
            illu:
              name: illu
              port: 8037
            # asvzla:
            #   name: asvzla
            #   port: 8038
            gabster:
              name: gabster
              port: 8039
            slump:
              name: slump
              port: 8040
            velinova:
              name: velinova
              port: 8041
            seven:
              name: seven
              port: 8042
            avalon747:
              name: avalon747
              port: 8043
            # krunalamin:
            #   name: krunalamin
            #   port: 8044
            # shadawn:
            #   name: shadawn
            #   port: 8045
            miguelaserrao:
              name: miguelaserrao
              port: 8046
            danielzamora87:
              name: danielzamora87
              port: 8047
            kendrickllama:
              name: kendrickllama
              port: 8048
            martc:
              name: martc
              port: 8049
            doglord:
              name: doglord
              port: 8050
            eriknuke98:
              name: eriknuke98
              port: 8051
            oxcel:
              name: oxcel
              port: 8052
            younggod:
              name: younggod
              port: 8053
            bass:
              name: bass
              port: 8054
            thefuckingleader:
              name: thefuckingleader
              port: 8055
            # jb:
            #   name: jb
            #   port: 8056
            ryanc:
              name: ryanc
              port: 8057
            traderi:
              name: traderi
              port: 8058
              stock: 1
            rody:
              name: rody
              port: 8059
            cryptohimbo:
              name: cryptohimbo
              port: 8060
            bingobango:
              name: bingobango
              port: 8061
            juffytosegovia:
              name: juffytosegovia
              port: 8062
            matan:
              name: matan
              port: 8063
            svrebelo:
              name: svrebelo
              port: 8064
            scott:
              name: scott
              port: 8065
            pokemonmania:
              name: pokemonmania
              port: 8066
        do2:
          ansible_host: 161.35.140.92
          scrape: 30s
          clients:
            pearson:
              name: pearson
              port: 8018
              stock: 2
            modbusmasterofnull:
              name: modbusmasterofnull
              port: 8019
              stock: 1
            jonesbooned:
              name: jonesbooned
              port: 8020
              crypto: 2
              stock: 3
            empros:
              name: empros
              port: 8021
              stock: 1
            # maylian:
            #   name: maylian
            #   port: 8022
            #   crypto: 1
            #   stock: 1
            sfr:
              name: sfr
              port: 8023
              crypto: 1
            cswxg:
              name: cswxg
              port: 8024
              crypto: 2
              stock: 1
            oracle:
              name: oracle
              port: 8025
            gghadid:
              name: gghadid
              port: 8027
            annetburton:
              name: annetburton
              port: 8028
            cotufa:
              name: cotufa
              port: 8030
            josh:
              name: josh
              port: 8031
            vortex:
              name: vortex
              port: 8032
            # chibi:
            #   name: chibi
            #   port: 8033    
            # jeruhmii:
            #   name: jeruhmii
            #   port: 8034
            fathom:
              name: fathom
              port: 8058
            drzaius:
              name: drzaius
              port: 8059
            troyzhou:
              name: troyzhou
              port: 8060
            captainwowuk:
              name: captainwowuk
              port: 8061
            demigod:
              name: demigod
              port: 8062
            gerion:
              name: gerion
              port: 8063
            ty13rrr0ok:
              name: ty13rrr0ok
              port: 8064
            chococha:
              name: chococha
              port: 8065
            metalwolf:
              name: metalwolf
              port: 8066
            iurynathan:
              name: iurynathan
              port: 8067
            cristofollis:
              name: cristofollis
              port: 8068
            coma:
              name: coma
              port: 8069
            wes2:
              name: wes2
              port: 8070
            rich:
              name: rich
              port: 8071
            nzaru:
              name: nzaru
              port: 8072
            sebmonty:
              name: sebmonty
              port: 8073
            banglh:
              name: banglh
              port: 8074
            darthvagitarian:
              name: darthvagitarian
              port: 8075
        do3:
          ansible_host: 161.35.128.202
          scrape: 30s
          clients:
            # meggymoon:
            #   name: meggymoon
            #   port: 8000
            sheepus:
              name: sheepus
              port: 8001
              crypto: 2
            richardtodd:
              name: richardtodd
              port: 8002
              crypto: 5
            chillywatermelon:
              name: chillywatermelon
              port: 8003
              crypto: 3
            hygge:
              name: hygge
              port: 8004
              crypto: 2
            cipher:
              name: cipher
              port: 8005
              crypto: 2
            witdawristshot:
              name: witdawristshot
              port: 8006
              crypto: 3
            # razermanic:
            #   name: razermanic
            #   port: 8007
            #   crypto: 4
            aetherean:
              name: aetherean
              port: 8008
              crypto: 1
            iamcharchar:
              name: iamcharchar
              port: 8009
              crypto: 1
            sarv-shaktimaan:
              name: sarv-shaktimaan
              port: 8010
              crypto: 1
            vectorsix:
              name: vectorsix
              port: 8011
              crypto: 1
            zooma:
              name: zooma
              port: 8012
              crypto: 1
            # shotie:
            #   name: shotie
            #   port: 8013
            #   crypto: 1
            ionut4a:
              name: ionut4a
              port: 8014
              crypto: 5
            chaneuwoo:
              name: chaneuwoo
              port: 8022
            besseralleine:
              name: besseralleine
              port: 8023
            lauty:
              name: lauty
              port: 8024
            berry:
              name: berry
              port: 8025
            # bulgogiman:
            #   name: bulgogiman
            #   port: 8026
            lucas:
              name: lucas
              port: 8027
            niftyplayerone:
              name: niftyplayerone
              port: 8028
            scylla:
              name: scylla
              port: 8029
            proxen:
              name: proxen
              port: 8030
            whoisoldgreg:
              name: whoisoldgreg
              port: 8031
            stevenc:
              name: stevenc
              port: 8032
            inago:
              name: inago
              port: 8033
            funferret:
              name: funferret
              port: 8034
            senzi:
              name: senzi
              port: 8035
            janis:
              name: janis
              port: 8036
            pinx:
              name: pinx
              port: 8037
            cryptostu:
              name: cryptostu
              port: 8038
            insaneyinyang:
              name: insaneyinyang
              port: 8039
            draft:
              name: draft
              port: 8040
            rimurutempest:
              name: rimurutempest
              port: 8041
            mrniceguybullybob:
              name: mrniceguybullybob
              port: 8042
            senseilambo:
              name: senseilambo
              port: 8043
            ariyana:
              name: ariyana
              port: 8044
        do4:
          ansible_host: 161.35.142.197
          scrape: 30s
          clients:
            vestro:
              name: vestro
              port: 8059
              stock: 1
            blooddiamond:
              name: blooddiamond
              port: 8060
              stock: 4
            thelastpolarbear:
              name: thelastpolarbear
              port: 8061
              stock: 1
            mishaj:
              name: mishaj
              port: 8062
              crypto: 1
            veilleux:
              name: veilleux
              port: 8017
            cacalillos:
              name: cacalillos
              port: 8018
            nftgaming:
              name: nftgaming
              port: 8019
            wizarddevv:
              name: wizarddevv
              port: 8020
            veilleuxalt:
              name: veilleux-alt
              port: 8021
            ely:
              name: ely
              port: 8022
            kean:
              name: kean
              port: 8023
            tomxnoo:
              name: tomxnoo
              port: 8024
            chakal:
              name: chakal
              port: 8025
            # eleducator:
            #   name: eleducator
            #   port: 8026
            locke:
              name: locke
              port: 8027
            colddoge:
              name: colddoge
              port: 8028
            brhino:
              name: brhino
              port: 8029
            oneone13:
              name: oneone13
              port: 8030
            hideyoshi:
              name: hideyoshi
              port: 8031
            hideyoshiphp:
              name: hideyoshi-php
              port: 8032
            mattwill:
              name: mattwill
              port: 8033
            jumpman:
              name: jumpman
              port: 8034
            edge:
              name: edge
              port: 8035
            livingoncrypto:
              name: livingoncrypto
              port: 8036
            thorhammer:
              name: thorhammer
              port: 8037
            bryant:
              name: bryant
              port: 8038
            mastablasta:
              name: mastablasta
              port: 8039
            ghost:
              name: ghost
              port: 8040
            mraygo:
              name: mraygo
              port: 8041
            lucci:
              name: lucci
              port: 8042
            bundy:
              name: bundy
              port: 8043
            hassie:
              name: hassie
              port: 8044
            spamton:
              name: spamton
              port: 8045
            albloshy:
              name: albloshy
              port: 8046
            abr:
              name: abr
              port: 8047
            tavernsideguides:
              name: tavernsideguides
              port: 8048
            elementor:
              name: elementor
              port: 8049
            themehrankhan:
              name: themehrankhan
              port: 8050
            pir8radio:
              name: pir8radio
              port: 8051
            fifth:
              name: fifth
              port: 8052
            jeremyc:
              name: jeremyc
              port: 8053
            antonio:
              name: antonio
              port: 8054
            joshuataylor:
              name: joshuataylor
              port: 8055
            axiekingdom:
              name: axiekingdom
              port: 8056