apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-daily
  namespace: longhorn-system
spec:
  cron: "0 10 * * *"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 1