apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: "27.14.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  releaseName: prometheus
  values:
    commonMetaLabels:
      cluster: cluster
    server:
      persistentVolume:
        enabled: false
      service:
        servicePort: 9090
        annotations: {}
      defaultFlagsOverride:
        - --storage.tsdb.retention.size=10GB
        - --config.file=/etc/config/prometheus.yml
    alertmanager:
      enabled: false
