apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=service
        - --registry=noop
        - --policy=upsert-only
        - --provider=webhook
        - --webhook-provider-url=http://localhost:8888
      - name: unifi-webhook
        image: ghcr.io/kashalls/external-dns-unifi-webhook:main
        ports:
        - containerPort: 8888
        env:
        - name: UNIFI_HOST
          value: "https://192.168.2.1"
        - name: UNIFI_SKIP_TLS_VERIFY
          value: "true"
        - name: UNIFI_API_KEY
          valueFrom:
            secretKeyRef:
              name: unifi-controller
              key: api
      securityContext:
        fsGroup: 65534