apiVersion: v1
kind: Namespace
metadata:
  name: localstack
 
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: localstack
  namespace: localstack
spec:
  repo: https://localstack.github.io/helm-charts
  chart: localstack
  targetNamespace: localstack
  valuesContent: |-
    service:
      type: LoadBalancer