---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgA56IjeHGLrpz/+Vw8PDqUYUvvio1lK4eNvv/I/3omePIRna5SndmnU9BHc/tGJrE5QyviPV7pWCiErt4UAhifkgn18zl3pzvEu/CEPQ6Sh+LDkcYrMyzpP3M5TkcKm/AWQTOnOnaqpeNqkWdyiuE3tYdWXQRpuqNmtqy3i8V1YZxloT9W6MRFo7/26zuT+pkYi8STTnHkkQaoYsa9AOsyETT3bKebf9beC3AStutsNgRKTZ2UrwW74iEc74uDsgYZW0y8worgA36cxEdSZncG9B2d626xKscnj5AsCVYRHw1NpmuOZgbAqEkR6MmyrCrg/2tZb8mWyAYhzjMfsZ8eAHkwTzE9HHyCnYDgSxxz2zPuaBk5lG07U+c8hnmbgBBNOLjtqE2k6BtxXZ+sXbzd3YPdtSezazjHv1o0+JrvOyrh3Hka2gVCv8TFHsbHAQ4o161Dh7iPas7lb51UX1Qn+TnDnlckJfypPYUI/2E59Rg6RplRsaZRNQrFfYw1QvGS9X9COH/DKbdjsGjE/RL6QLDngBKiZR/z32/44axEfV/2MQQwSSpH3ZOBs2QE1R8cBScjNqyXwuKHd9cTKYNjV3mdNzUUBG+nmfav/JWmBwkaLIZr4Q+WGL05heGXY97P1bcTOY7GxemmFqCAriiAeLjl8n3+OgX5qwuZCv7djLBv24EwlsWQp8zyR76q1i7fX7FwAWpGpAA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pihole
      namespace: kube-system
    type: Opaque

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        envFrom:
        - secretRef:
            name: pihole
        args:
        - --source=service
        - --registry=noop
        - --policy=upsert-only
        - --provider=pihole
        - --pihole-server=http://192.168.2.2:8888/
      securityContext:
        fsGroup: 65534