apiVersion: v1
kind: Namespace
metadata:
  name: signal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-api
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-api
  template:
    metadata:
      labels:
        app: signal-api
    spec:
      containers:
      - name: signal-api
        image: bbernhard/signal-cli-rest-api:0.91
        imagePullPolicy: Always
        env:
        - name: SIGNAL_CLI_CONFIG_DIR
          value: /signal
        - name: LOG_LEVEL
          value: debug
        - name: MODE
          # json-rpc
          value: json-rpc
        # - name: AUTO_RECEIVE_SCHEDULE
        #   value: "0 0 * * *"
        ports:
        - name: api
          containerPort: 8080
        volumeMounts:
        - name: signal-data
          mountPath: /signal
        livenessProbe:
          httpGet:
            path: /v1/health
            port: api
        readinessProbe:
          httpGet:
            path: /v1/health
            port: api
      volumes:
      - name: signal-data
        persistentVolumeClaim:
          claimName: signal-api-v2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-api-v2
  namespace: signal
spec:
  # volumeName: pvc-565ab154-e062-44ed-8a9c-76f2e475b25d
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250M

---
apiVersion: v1
kind: Service
metadata:
  name: signal-api
  namespace: signal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: signal-api.r.ss
spec:
  type: LoadBalancer
  selector:
    app: signal-api
  ports:
  - name: api
    port: 80
    targetPort: api





{
  "captcha": "signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5Ijoia2RLUks5Zk5BZjdnOVdUTmlxcXFROEhJbFlSVTVobDFJUmpOOE95elFWbTZ0dTZNMUllUEVjNEx0QWtJRm9xeC96V1p0WDBxZnVwc05GaTMvcy81RGhkN3dOTklGUmtvcTB0VWNVRzNjNm1PWXJOandhVmJPcFc3dFlTbDkxSkR0Ymo3N1N5WjcxMmRjREcxNmQ4U0NBYzlxWDRGaFRDVWd3dVh2WUt2UHpWUC8rOVRvNkxPdHZnZklJWDI1QzRhNE9aQmZ2UlVwVHNnSDJ5K3hmaUphcHdlWU1pUjkvS0dzeDdnb29qbUhZYTgxa25wcFFlUEVXR3AyZUYzU2FTMkE1eFZyQ0xnazA2dTg4eDRTUi94bkpmSW1PbXRydHJxR1lYY3N1Qkpha1QxNDkzdnVEZnpRaTJpOTZRNnhZSVl4aThibEV1OWdsZmNIUm1XMUlhS0xHaXhqVjd6S0FKai9uNTgxaE8vV01rajVLMlpjU0xqbno1VWxBM1kzeTBNcHZwRGUyblVkZXB0TmlQaEdGOWwxNGlXWDlFV1hjTzdVNFVBUDlBbWxmaXI5R0NzWm93bzlCQVNMWnhsSm5OQ29kbTZSV25zUGxqcFJqQm9lM3lFQTc2UzBsb3VVZDZmZ2lKQnorOWsyNndNMGU0Q2VCd1Q2TG52U0p4SDg1VWVXTWsvdE1uaUc0ZU5ZQ3dvNldDcitKQVE5eGhhTnhuK3ZvemJORVBIWWZ0eWpWalJvNmRPUDh2ODBVQ1VucVJlS0lHbFhCa05pbjNXOHZDTUhSQ0JuQldOblZ1eW9yTWtNSVZXOCt2cjJVSndyZEJqd0lrNHNudFdwSjluWWV0eU1nUXFSSjBGdEFDNU1MZXcwR3F6R083amYxeHZaWEpTa3lHUkhUb2tHRW9QSVRjMHZmdXBNNWFYTGNDNGtKYllyb01BVmpxQk9EaVNpM1M1ekJmbVpneDIzUVB3UkN2a0lSTDYwbEVqTGpmejM5L2Jicml3d1VZT0xSMWNoT3dPTEZzU2ZmU25UdDc2WkxmM2h6TVhKT1NXVGJqVWhTaEZoNjVRQWQzaVJlSmJYdWxSN2lnb2xuK29GRUd3dEN6WStGTnRwUEZEZ0RrQVlhbkR2NDJFSXpuZ2ZkUm9hMjNjc0NhVjJHb0ZzeTJJZHFxcmdpakpXclVPYlVzdHBQZVJsbUx2bVVvZExDUVAvRDZyaVVLa2ZPSEtyUTZQZDlGbVNBWHFVMHlxbnFjQ1VrSndEblZNdldwajR0d25qTUxVcExnWDEvdzZIQ00wZld2cFlpYnVwVEFPMlExRGxaUGVPcGZlWUFISHZ4UWM0QUxyazkvRjlPYmRuNjFCc2dsaW5pY1ZzQWgwNUFoamw1bnlhVmJ4elNqcm0yQjNZaXozZkMxRVpEcWh0ejl5dGtNTUhJQnB2K2Nlb0lFQXArMDIrNGcwUUVrVmNkaDl2NHVDSi9qcjEyaCszSnRrczMwZHhpMG5RbitOYS9OSkhnMWk2RTU3Z2NHcFh1T0FuVXErK0MzVUZRd3F2UlVlU2ZwN2ZoSHBUQWNud25IWUNOOGc0NXN6TDkvMURqYlkzNHUxWERBZnRJN05wVDZXazFkd3dBSjV6Qi9NNE5LSm5vejMwK3NHVVlGMGVER3h4R2ZNL3k1SEZNM1RkT1pKNmJlK0libVJJTFJ5RExlQnVRVHRGeU8xempwTjJxU0dlWEMvNmRhNkV6d2c1ZGdRRHJxTlNMMTNLcDNjcHJ5MzhwcHF0TERzOExDVVlGTzZ4Rng2VjJTekVVZmkwTTRwMG1rQlJkNStIdjBmQUNmdVduZWdKUmkxSG9jbVBUVGFZbzliTUJmNGtTajZGcUhwQWtPa3ozV3lHWml6TGxCdStuL2ozdmNtUW1CYnMvWlJjeXZKaWlnUGRXZkRUaUsrdkI5cUs4M3BaaWpnN1VWSnZ3eXpTa1J1a0RiVEpFWGpzTVV2a0VhRUJoZHVUbHNrNDBKRXFSaUFraUdyTS96SDh5WU5VRjUwV2VFSzRnbzZaR2t0QmVJYjMreTN3UDZ5T29DU0JYdW5oSkdaYzNob3RGb0pSRUQ1R1JkdjVPSllQOXZNWlowQnBNM2dvQlZVb3BBOU5MSWhqdzltdThrdkh1SGorclFNb0lwZ3R4QXE5RFp3MEIyZnR1azByVEFqZytucFo2eklZcnRsdDJJa1RtUTIvTGVQeFYzWU5aWUpVSkZlRTM4N01ldUZuanFzVFF3WEpwdlI2NWhmdGRIc2NJMHFZTjArSERvaHp3SzlTNURZZjM5ckxmSWtaMUVvRzBLdy81Y2NTZGc0MzRSVElmRnNzM3N1RTlsM0hUSUU0eFhwM1lTWUcxazN1THhrM29uUUg1Z3ZHbFFDWk9NcVBaR1JnMVQybGRmclFCd3duTitjc3E5Njk1ZlBpUGR1UkYwQ1VBZlFJdmpTUElYY0tBekE0MkRsSXpmdHpoSGU4WFM4RWFyRVlNZlRKOEpZRmFjS1VnMDZmazljbm9QUDdLZ21iVEp3IiwiZXhwIjoxNzQ1NjE3NDY0LCJzaGFyZF9pZCI6ODMzNDQwODk3LCJrciI6IjI0YmFlZWJkIiwicGQiOjB9.YwByZod5GYmQ4MVVWlQSaFgBzX5GE6bcFCRYZYDFZjY",
  "use_voice": false
}
