apiVersion: v1
kind: Namespace
metadata:
  name: signal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-api
  namespace: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-api
  template:
    metadata:
      labels:
        app: signal-api
    spec:
      containers:
      - name: signal-api
        image: bbernhard/signal-cli-rest-api:0.89
        imagePullPolicy: Always
        env:
        - name: SIGNAL_CLI_CONFIG_DIR
          value: /signal
        - name: MODE
          # json-rpc
          value: json-rpc
        # - name: AUTO_RECEIVE_SCHEDULE
        #   value: "0 0 * * *"
        ports:
        - name: api
          containerPort: 8080
        volumeMounts:
        - name: signal-data
          mountPath: /signal
        livenessProbe:
          httpGet:
            path: /v1/health
            port: api
        readinessProbe:
          httpGet:
            path: /v1/health
            port: api
      volumes:
      - name: signal-data
        persistentVolumeClaim:
          claimName: signal-api

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-api
  namespace: signal
spec:
  volumeName: pvc-565ab154-e062-44ed-8a9c-76f2e475b25d
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250M

---
apiVersion: v1
kind: Service
metadata:
  name: signal-api
  namespace: signal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: signal-api.r.ss
spec:
  type: LoadBalancer
  selector:
    app: signal-api
  ports:
  - name: api
    port: 80
    targetPort: api

# register new number with signal
# curl -X POST http://signal-api.r.ss/v1/register/+14808407117 --data '{
#   "captcha": "signal-hcaptcha.xxxx",
#   "use_voice": false
# }'

# verify with text recived
# curl -X POST http://signal-api.r.ss/v1/register/+14808407117/verify/803209

# add device from qr code
# curl -X POST http://signal-api.r.ss/v1/devices/+14808407117 --data '{
#   "uri": "sgnl://linkdevice?uuid=xxxx&pub_key=xxxx"
# }'

# recive messages
# curl http://signal-api.r.ss/v1/receive/+14808407117 | jq .

# send to riley
# curl -X POST http://signal-api.r.ss/v2/send --data '{
#   "message": "feed me",
#   "number": "+14808407117",
#   "recipients": [
#     "+15159792049"
#   ]
# }'

# curl -X POST http://signal-api.r.ss/v1/reactions/+14808407117 --data '{
#   "reaction": "👍",
#   "recipient": "+15159792049",
#   "target_author": "+15159792049",
#   "timestamp": 1712269034633
# }'

# send to nicole
# curl -X POST http://signal-api.r.ss/v2/send --data '{
#   "message": "hello mom, love you",
#   "number": "+14808407117",
#   "recipients": [
#     "+15155097579"
#   ]
# }'


# curl -X POST http://oca0:8273/v2/send --data "
#   {
#     \"message\": \"test\",
#     \"number\": \"+14808407117\",
#     \"recipients\": [
#       \"+15159792049\"
#     ]
#   }"


# curl oca0:8273/v1/configuration --data '	
# {
#   "logging": {
#     "Level": "debug"
#   }
# }'
