---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ff-proxy
spec:
  repo: https://rssnyder.github.io/charts
  chart: ff-proxy
  targetNamespace: default
  valuesContent: |-
    proxyKey: 55f07224-59bc-430c-abad-c0c631252fb2
    authSecret: fooBar
    redis:
      address: redis.redis:6379
    image:
      repository: rssnyder/ff-proxy
      pullPolicy: Always
      tag: os
    writer:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Gi
      securityContext:
        runAsUser: 65555
    readReplica:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ff-proxy
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ff-proxy.k8s.rileysnyder.dev
      http:
        paths:
          - path: /ff-proxy(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name:  ff-proxy-read-replica
                port:
                  number: 7000
