
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kyverno
spec:
  repo: https://kyverno.github.io/kyverno
  chart: kyverno
  targetNamespace: kyverno
