---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: immich
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ k8s.secrets.cnpg.AWS_SECRET_KEY_ID | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ k8s.secrets.cnpg.AWS_SECRET_ACCESS_KEY | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ k8s.secrets.cnpg.AWS_SECRET_KEY_ID | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ k8s.secrets.cnpg.AWS_SECRET_ACCESS_KEY | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-token
  namespace: dnd-generator
data:
  .dockerconfigjson: {{ k8s.secrets.ghcr_docker_config }}
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: dnd-generator
  namespace: dnd-generator
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.dnd_generator.PG_PASSWORD | b64encode }}
  AWS_SECRET_KEY_ID: {{ k8s.secrets.dnd_generator.AWS_SECRET_KEY_ID | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ k8s.secrets.dnd_generator.AWS_SECRET_ACCESS_KEY | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: counter
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.counter.PG_PASSWORD | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: keys
type: Opaque
data:
  username: keys
  password: {{ k8s.secrets.kkeys.postgres.password | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pushover
  namespace: reddit-alerts
type: Opaque
data:
  app: {{ k8s.secrets.reddit_alerts.pushover.app | b64encode }}
  user: {{ k8s.secrets.reddit_alerts.pushover.user | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot
  namespace: discord-bot
type: Opaque
data:
  token: {{ k8s.secrets.discord_bot.token | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-manager
  namespace: discord-bot-manager
type: Opaque
data:
  pgpassword: {{ k8s.secrets.discord_bot_manager.pgpassword | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
type: Opaque
data:
  pgpassword: {{ k8s.secrets.survivor_tracker.pgpassword | b64encode }}
  tautullipassword: {{ k8s.secrets.survivor_tracker.tautullipassword | b64encode }}