config:
  burrito:
    datastore:
      storage:
        s3:
          bucket: burrito
          usePathStyle: true
    runner:
      image:
        repository: rssnyder/burrito
        tag: dev

datastore:
  deployment:
    envFrom:
    - secretRef:
        name: minio
        
server:
  service:
    type: LoadBalancer

tenants:
- namespace:
    create: true
    name: "isengard"
  serviceAccounts:
  - name: "isengard"
