apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  url: https://bitnami-labs.github.io/sealed-secrets

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.17.2"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 5m
  releaseName: sealed-secrets
  values:
    fullnameOverride: sealed-secrets-controller
