---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 5m
  releaseName: external-secrets
  values:
    installCRDs: true
    serviceAccount:
      create: true
      name: external-secrets
    webhook:
      enabled: true
      port: 10250
