apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infrastructure/base/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 1h
  path: ./k8s/infrastructure/k/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infrastructure/base/cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infrastructure/base/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets-secrets
  interval: 1h
  path: ./k8s/infrastructure/base/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infrastructure/base/metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-system
  interval: 1h
  path: ./k8s/infrastructure/base/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
        - op: replace
          path: /spec/addresses
          value:
          - 192.168.253.1-192.168.253.254
      target:
        kind: IPAddressPool
        name: local
        namespace: metallb-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets-secrets
  interval: 1h
  path: ./k8s/infrastructure/base/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
        - op: replace
          path: /spec/values/defaultBackupStore/backupTarget
          value: s3://longhorn@us-east-1/k/backups
      target:
        kind: HelmRelease
        name: longhorn
        namespace: longhorn-system
