---
version: "3"
services:

{{ alloy_compose | to_nice_yaml(indent=2) | indent(2, first=True) }}

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./open-webui:/app/backend/data


volumes:
  alloy_data: