---
version: "3"
services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    # command: vllm serve google/gemma-4-31B-it
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - ./open-webui:/app/backend/data
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
