
apiVersion: v1
kind: Namespace
metadata:
  name: coder

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: survivor
  namespace: coder
spec:
  repo: https://rssnyder.github.io/external-charts
  chart: code-server
  targetNamespace: coder
  valuesContent: |-
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: true
      hosts:
       - host: survivor-coder.k8s.rileysnyder.dev
         paths:
           - /
      ingressClassName: "nginx"
    persistence:
      size: 10Gi
      storageClass: "longhorn"
    extraVars:
    - name: DISABLE_TELEMETRY
      value: "true"
    - name: DOCKER_HOST
      value: "tcp://localhost:2375"
    extraContainers: |
      - name: docker-dind
        image: docker:19.03-dind
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256M
        securityContext:
          privileged: true
          procMount: Default
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_DRIVER
          value: "overlay2"