apiVersion: v1
kind: Namespace
metadata:
  name: kube-amd-gpu

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: amd-gpu-operator
  namespace: kube-amd-gpu
spec:
  repo: https://rocm.github.io/gpu-operator
  chart: gpu-operator-charts
  targetNamespace: kube-amd-gpu
  valuesContent: |-
    controllerManager:
      nodeSelector:
        kubernetes.io/hostname: jack
