apiVersion: v1
kind: Namespace
metadata:
  name: frigate

---
apiVersion: v1
data:
  auth: {{ nginx_ingress_auth_secret }}
kind: Secret
metadata:
  name: basic-auth
  namespace: frigate
type: Opaque

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  namespace: frigate
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
    - host: frigate.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  frigate
                port:
                  number: 80

