---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ff-proxy-writer
  namespace: ff-relay-proxy-helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: ff-proxy-writer
  podMetricsEndpoints:
  - port: sdk

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ff-proxy-read-replica
  namespace: ff-relay-proxy-helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: ff-proxy-read-replica
  podMetricsEndpoints:
  - port: sdk