# apiVersion: v1
# kind: Namespace
# metadata:
#   name: minio

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: minio
#   namespace: minio
# type: Opaque
# data:
#   MINIO_ROOT_PASSWORD: {{ k8s.secrets.minio.root_password | b64encode }}

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: minio
#   namespace: minio
# spec:
#   selector:
#     matchLabels:
#       app: minio
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: minio
#     spec:
#       nodeName: charlie
#       containers:
#       - name: minio
#         image: quay.io/minio/minio
#         command: ["minio"]
#         args: ["server", "/data", "--console-address", ":9001"]
#         env:
#         - name: MINIO_ROOT_USER
#           value: "admin"
#         - name: MINIO_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: minio
#               key: MINIO_ROOT_PASSWORD
#         ports:
#         - name: api
#           containerPort: 9000
#         - name: webui
#           containerPort: 9001
#         volumeMounts:
#         - name: data
#           mountPath: /data
#       volumes:
#       - name: data
#         hostPath:
#           path: /mnt/bulk/k8s/minio

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
#   namespace: minio
#   annotations:
#     tailscale.com/expose: "true"
#     tailscale.com/hostname: "minio"
#     external-dns.alpha.kubernetes.io/hostname: minio.r.ss
# spec:
#   type: LoadBalancer
#   selector:
#     app: minio
#   ports:
#   - name: http
#     port: 80
#     targetPort: api
#   - name: webui
#     port: 9001
#     targetPort: webui
