

---
apiVersion: v1
kind: Secret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
type: Opaque
data:
  pgpassword: {{ k8s.secrets.survivor_tracker.pgpassword | b64encode }}
  tautullipassword: {{ k8s.secrets.survivor_tracker.tautullipassword | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: google-sheets-service-account
  namespace: python-functions
type: Opaque
data:
  creds: {{ k8s.secrets.python_functions.google_sheets_service_account_json }}
