---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb
  namespace: frigate
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500G
  hostPath:
    path: "/mnt/hdd/k3s/frigate"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate
  namespace: frigate
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: frigate
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homeassistant.frigate.r.ss
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frigate
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  - name: rtmp
    port: 1935
    targetPort: 1935
  - name: go2rtc
    port: 8554
    targetPort: 8554