image:
  tag: 0.14.0
fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    external-dns.alpha.kubernetes.io/hostname: frigate.r.ss
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: "ffmpeg:http://192.168.0.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      lab: "rtsp://admin:admin@192.168.0.95:554/cam/realmonitor?channel=1&subtype=0"
      lab_sub: "rtsp://admin:admin@192.168.0.95:554/cam/realmonitor?channel=1&subtype=0"
      # roam: "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      # roam_sub: "ffmpeg:http://192.168.0.96/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
  cameras:
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: true
        # events:
        #   required_zones:
        #   - door
        #   - car
      snapshots:
        required_zones:
          - door
          - car
      zones:
        door:
          coordinates: 592,291,544,291,542,322,578,325
          objects:
            - dog
        car:
          coordinates: 0,672,766,672,807,423,351,350,0,422
          objects:
          - car
      objects:
        track:
          # - person
          - dog
          - car
    # louie:
    #   ffmpeg:
    #     inputs:
    #       - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.98:554/h264Preview_01_main
    #   record:
    #     enabled: false
    #   detect:
    #     enabled: false
    #   onvif:
    #     host: 192.168.0.98
    #     port: 8000
    #     user: admin
    #     password: <+secrets.getValue("default_lab_password")>
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.0.99:554/h264Preview_01_main
            roles:
              - detect
      detect:
        width: 2560
        height: 1440
      record:
        enabled: true
        # events:
        #   required_zones:
        #   - yard
      snapshots:
        required_zones:
          - yard
      objects:
        mask:
          - 2174,918,2218,1217,2103,1377,1836,1379,1830,1189,1852,963,2052,665
        track:
          - person
          - car
      motion:
        mask:
          - 2174,918,2218,1217,2103,1377,1836,1379,1830,1189,1852,963,2052,665
      zones:
        yard:
          coordinates: 0,1440,2560,1440,2560,1140,1844,1116,1533,1102,1161,1084,738,1049,0,1009
          objects:
            - person
        driveway:
          coordinates: 2560,1440,2061,1440,2170,1041,2342,1041,2560,1153
          objects:
            - car
      onvif:
        host: 192.168.0.99
        port: 8000
        user: admin
        password: <+secrets.getValue("default_lab_password")>
    # roam:
    #   ffmpeg:
    #     inputs:
    #     - path: rtsp://127.0.0.1:8554/roam?video=copy&audio=aac
    #       input_args: preset-rtsp-restream
    #       roles:
    #         - record
    #     - path: rtsp://127.0.0.1:8554/roam_sub?video=copy
    #       input_args: preset-rtsp-restream
    #       roles:
    #         - detect
    #   detect:
    #     width: 2560
    #     height: 1920
    #   record:
    #     enabled: true
    # garage:
    #   ffmpeg:
    #     inputs:
    #       - path: rtsp://wyze-bridge:8554/garage-door
    #         roles:
    #           - detect
    #   record:
    #     enabled: true
    # amcrest1:
    #   ffmpeg:
    #     inputs:
    #       - path: rtsp://admin:admin@192.168.0.119:554/cam/realmonitor?channel=1&subtype=0
    #   record:
    #     enabled: false
    #   detect:
    #     enabled: false
    lab:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/lab?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lab_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: false
      detect:
        enabled: false
      motion:
        mask:
          # laundry
          - 2320,125,2199,872,1828,991,1914,53
          # chair
          - 884,1847,1342,1516,916,1181,560,1328
      objects:
        mask:
          - 2320,125,2199,872,1828,991,1914,53
          - 884,1847,1342,1516,916,1181,560,1328
  # snapshots:
  #   enabled: True
  #   timestamp: True
  #   retain:
  #     default: 365
  objects:
    filters:
      person:
        # Optional: minimum score for the object to initiate tracking (default: shown below)
        min_score: 0.7
        # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
        threshold: 0.8
persistence:
  media:
    enabled: True
    existingClaim: media
nodeSelector:
  kubernetes.io/hostname: charlie
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi