image:
  tag: 0.16.0
fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    external-dns.alpha.kubernetes.io/hostname: frigate.r.ss
persistence:
  media:
    enabled: True
    existingClaim: frigate
# extraVolumes:
# - name: snapshot-html
#   image:
#     reference: rssnyder/frigate-snapshot-html:latest
#     pullPolicy: Always
# extraVolumeMounts:
# - name: snapshot-html
#   mountPath: /opt/frigate/web/snapshots
nodeSelector:
  kubernetes.io/hostname: jack
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: "ffmpeg:http://192.168.2.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: "ffmpeg:http://192.168.2.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      lab: "rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.95:554/cam/realmonitor?channel=1&subtype=0"
      lab_sub: "rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.95:554/cam/realmonitor?channel=1&subtype=0"
      front: "rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0"
      front_sub: "rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0"
  detect:
    enabled: True
  face_recognition:
    enabled: True
  lpr:
    enabled: True
    enhancement: 0
    debug_save_plates: True
    known_plates:
      altima:
      - "FAV 96"
      camery:
      - "IJN 189"
  record:
    enabled: True
    retain:
      days: 3
      mode: all
    detections:
      retain:
        days: 90
  snapshots:
    enabled: True
    retain:
      default: 730
    quality: 100
    bounding_box: True
    crop: False
  semantic_search:
    enabled: True
    reindex: True
  genai:
    enabled: True
    provider: ollama
    model: "llava:13b"
    base_url: "http://192.168.2.4:11434"
    prompt: "Describe the {label} in the sequence of images in a concise sentence, be straight and to the point. Do not mention 'sequence of images'. The images are from a security camera, do not mention this. Do not describe the background."
  cameras:
    front:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: true
      detect:
        enabled: true
      motion:
        mask:
          - 1,0.318,0.474,0.112,0.347,0.117,0.19,0.18,0.182,0.182,0.126,0.053,0.201,0,1,0
          - 0.704,0.257,0.761,0.268,0.763,0.487,0.713,0.562,0.658,0.569,0.618,0.482,0.627,0.349
          - 0.226,0.079,0.221,0.3,0.279,0.332,0.339,0.323,0.347,0.238,0.333,0.148,0.283,0.086
      zones:
        yard:
          coordinates: 0.358,0.149,0.55,0.198,0.803,0.286,0.554,1,0,1,0,0.74,0.229,0.543,0.184,0.23
          objects:
            - person
            - car
            - dog
        driveway:
          coordinates: 0.927,0.374,0.968,0.664,0.963,0.733,0.73,0.607,0.814,0.322
          objects:
            - person
            - car
            - dog
      review:
        detections:
          required_zones:
            - yard
            - driveway
        alerts:
          required_zones:
            - yard
            - driveway
      snapshots:
        required_zones:
          - yard
          - driveway
      objects:
        track:
          - person
          - car
          - dog
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      review:
        detections:
          required_zones:
            - door
            - yard
        alerts:
          required_zones:
            - door
            - yard
      snapshots:
        required_zones:
          - door
          - yard
      zones:
        door:
          coordinates: 0.661,0.433,0.599,0.431,0.566,0.503,0.661,0.511
          objects:
            - dog
        yard:
          coordinates: 0,1,1,1,0.978,0.491,0.882,0.487,0.902,0.348,0.503,0.342,0.5,0.461,0.402,0.459,0,0.522
          objects:
          - car
          - person
          - cat
      motion:
        mask: 0,0.518,0.404,0.458,0.497,0.458,0.502,0.339,0.902,0.347,0.883,0.486,0.98,0.491,0.983,0.513,1,1,1,0,0,0
      objects:
        track:
          - dog
          - car
          - person
          - cat
    garage:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.99:554/h264Preview_01_main
            roles:
              - record
              - detect
      onvif:
        host: 192.168.2.99
        port: 8000
        user: admin
        password: <+secrets.getValue("default_lab_password")>
      objects:
        track:
          - person
      record:
        enabled: false
      detect:
        enabled: false
    lab:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/lab?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lab_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: false
      detect:
        enabled: false
      objects:
        track:
          - person
      # motion:
      #   mask:
      #     # laundry
      #     - 2320,125,2199,872,1828,991,1914,53
      #     # chair
      #     - 884,1847,1342,1516,916,1181,560,1328
      # objects:
      #   mask:
      #     - 2320,125,2199,872,1828,991,1914,53
      #     - 884,1847,1342,1516,916,1181,560,1328
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.98:554/h264Preview_01_main
      record:
        enabled: false
      detect:
        enabled: false
      onvif:
        host: 192.168.2.98
        port: 8000
        user: admin
        password: <+secrets.getValue("default_lab_password")>
  objects:
    filters:
      person:
        min_score: 0.7
        threshold: 0.8
      dog:
        min_score: 0.7
        threshold: 0.8
      cat:
        min_score: 0.7
        threshold: 0.8
      car:
        min_score: 0.7
        threshold: 0.8
