image:
  tag: 0.14.0
fullnameOverride: frigate
service:
  type: LoadBalancer
  port: 80
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    external-dns.alpha.kubernetes.io/hostname: frigate.r.ss
persistence:
  media:
    enabled: True
    existingClaim: frigate
nodeSelector:
  kubernetes.io/hostname: jack
coral:
  enabled: true
  hostPath: /dev/bus/usb
resources:
  requests:
    cpu: 1500m
    memory: 2Gi
config: |
  mqtt:
    host: "mosquitto.mosquitto"
    port: 1883
  database: 
    path: /media/frigate.db
  detectors:
    coral:
      type: edgetpu
      device: usb
  go2rtc:
    streams:
      back: "ffmpeg:http://192.168.2.97/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>#video=copy#audio=copy#audio=opus"
      back_sub: "ffmpeg:http://192.168.2.97/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<+secrets.getValue("default_lab_password")>"
      lab: "rtsp://admin:<+secrets.getValue("amcrest_password")>@192.168.2.95:554/cam/realmonitor?channel=1&subtype=0"
      lab_sub: "rtsp://admin:<+secrets.getValue("amcrest_password")>@192.168.2.95:554/cam/realmonitor?channel=1&subtype=0"
      front: "rtsp://admin:<+secrets.getValue("amcrest_password")>@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0"
      front_sub: "rtsp://admin:<+secrets.getValue("amcrest_password")>@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0"
      blx1c: "ffmpeg:rtsps://bblp:<+secrets.getValue("blx1c_cloud_key")>@192.168.2.79:322/streaming/live/1"
  record:
    enabled: True
    retain:
      days: 0
      mode: all
    events:
      retain:
        default: 30
        mode: motion
  cameras:
    front:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: true
      detect:
        enabled: true
      motion:
        mask:
          - 1,0.318,0.474,0.112,0.347,0.117,0.19,0.18,0.182,0.182,0.126,0.053,0.201,0,1,0
          - 0.704,0.257,0.761,0.268,0.763,0.487,0.713,0.562,0.658,0.569,0.618,0.482,0.627,0.349
          - 0.226,0.079,0.221,0.3,0.279,0.332,0.339,0.323,0.347,0.238,0.333,0.148,0.283,0.086
      zones:
        yard:
          coordinates: 0.348,0.128,0.545,0.175,0.814,0.28,0.498,0.995,0.003,0.997,0,0.409
          objects:
            - person
        driveway:
          coordinates: 0.928,0.323,0.981,0.669,0.976,0.815,0.687,0.716,0.825,0.278
          objects:
            - person
            - car
      review:
        detections:
          required_zones:
            - yard
            - driveway
        alerts:
          required_zones:
            - yard
            - driveway
      snapshots:
        required_zones:
          - yard
          - driveway
      objects:
        track:
          - person
          - car
    back:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      review:
        detections:
          required_zones:
            - door
        alerts:
          required_zones:
            - door
      snapshots:
        required_zones:
          - door
      zones:
        door:
          coordinates: 0.661,0.433,0.607,0.433,0.601,0.508,0.633,0.523
          objects:
            - dog
        car:
          coordinates: 0,672,766,672,807,423,351,350,0,422
          objects:
          - car
      motion:
        mask: 0,0.627,0.39,0.518,0.594,0.559,0.605,0.429,0.663,0.429,0.624,0.567,0.903,0.625,0.856,1,1,1,1,0,0,0
      objects:
        track:
          - dog
          - car
    garage:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.99:554/h264Preview_01_main
            roles:
              - record
              - detect
      onvif:
        host: 192.168.2.99
        port: 8000
        user: admin
        password: <+secrets.getValue("default_lab_password")>
      objects:
        track:
          - person
      record:
        enabled: false
      detect:
        enabled: false
    lab:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/lab?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lab_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      record:
        enabled: false
      detect:
        enabled: false
      # motion:
      #   mask:
      #     # laundry
      #     - 2320,125,2199,872,1828,991,1914,53
      #     # chair
      #     - 884,1847,1342,1516,916,1181,560,1328
      # objects:
      #   mask:
      #     - 2320,125,2199,872,1828,991,1914,53
      #     - 884,1847,1342,1516,916,1181,560,1328
    blx1c:
      ffmpeg:
        inputs:
        - path: rtsp://127.0.0.1:8554/blx1c?video=copy
          input_args: preset-rtsp-restream
      record:
        enabled: false
      detect:
        enabled: false
    louie:
      ffmpeg:
        inputs:
          - path: rtsp://admin:<+secrets.getValue("default_lab_password")>@192.168.2.98:554/h264Preview_01_main
      record:
        enabled: false
      detect:
        enabled: false
      onvif:
        host: 192.168.2.98
        port: 8000
        user: admin
        password: <+secrets.getValue("default_lab_password")>
  objects:
    filters:
      person:
        # Optional: minimum score for the object to initiate tracking (default: shown below)
        min_score: 0.7
        # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
        threshold: 0.8
