apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/manifests/oci/23/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/manifests/oci/23/cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/manifests/oci/23/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/manifests/lab/k/metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-system
  interval: 1h
  path: ./k8s/manifests/lab/k/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |
        - op: replace
          path: /spec/addresses
          value:
          - 192.168.253.1-192.168.253.254
      target:
        kind: IPAddressPool
        name: local
        namespace: metallb-system
