apiVersion: v1
kind: Namespace
metadata:
  name: keys

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: keys
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "s3://cnpg/micro/keys"
      endpointURL: https://s3.rileysnyder.dev
      s3Credentials:
        accessKeyId:
          name: minio
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: minio
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: db
  namespace: keys
spec:
  schedule: "0 0 * * * *"
  backupOwnerReference: cluster
  immediate: false
  cluster:
    name: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keys
  namespace: keys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keys
  template:
    metadata:
      labels:
        app: keys
    spec:
      containers:
      - name: keys
        image: rssnyder/keys:test
        imagePullPolicy: IfNotPresent
        env:
        - name: GIN_MODE
          value: release
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: db-app
              key: dbname
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: db-app
              key: username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-app
              key: password
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: db-app
              key: host
        ports:
        - name: api
          containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keys
  namespace: keys
spec:
  ingressClassName: nginx
  rules:
    - host: keys.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  keys
                port:
                  number: 80
