---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: pihole
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: operator-oauth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: delegate-token
  namespace: harness-delegate-ng
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: delegate-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: work-delegate-token
  namespace: harness-delegate-ng
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: work-delegate-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: work-shared-delegate-token
  namespace: harness-delegate-ng
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: work-shared-delegate-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: survivor-tracker
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: proxmox-cloud-controller-manager
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi
  namespace: kube-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: proxmox-csi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: harbor-admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: garage-rpc-secret