apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://bao.r.ss:8199"
      path: "pvekv"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "pve"
          # serviceAccountRef:
          #   audiences:
          #   - vault

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secretsbao-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets