---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: b4w
spec:
  encryptedData:
    .dockerconfigjson: AgAphI3aa3MzR5pmJR1I1YD7T37D8Y+pJ9exPtfl5HpPlNauz8Tfmd5DakgkRZD6VL3kmTWVXeKheNbrG/FwRiEhHhM1riuWfb/4KbMmKJ/Hxf+txF678+9sAImc5WKxGfM/CaRxqoUS+uICezenuFGUx3gMyR20OaaBomxbu9uDSXi6Fp+fRpJpTkQRm28Zdx9KrhZqlmHbF8ajdG7qbAWIs1BtWa861GDEShBsX46a2RQpK+PJOWvjrF1CPRBk6aFEiXhiHh0HJYuLlGk9KSEthKH1GZ77XUu0l0PosJmC8bZQxdV8wfFhezu2gJk472M0IDmRPBdifrVNz9Bd/HbaVeHadmPhXOyUQquSCkml6FAtKrFPu/ogw0ZwYs2zIZiiU0j2gz9OOZh9v7qPFsaIjED1bt/sTTcuDgi6jTBCWoPwouNuaSZ7NMpD1cRhnq7EWknVVRDBwvIoDZi5873qAisG4BA14vZ3Ia1GvDmqEld/wH+fdcwHGBF/2Va7Df9cZTJWeGYj/NiGOOjiRIFhPP1It9Uk55cgAhMcIF4UWkRjCazYobi1JJVYA2qX4HVLFNtKe/zo7oP/VvO5ZP0LrHnejqKDza0oaYetaqlHSZgncCayw4JhZgef6by/ai+kxsF2nQg8hQN8N1JhYOgavUKq1hOnfP/HXIeSAqzp3ERQCCYnYIgAeHi+8lHz8m49VlieEx0AkYQTtaodOgLSE/3TClcFLofpfJRUUCp0F7mdBep2jaNGmDzgCStwMTHSCWdGOreguBiuFYxVDuN3IelAsAqx8DxQk52dcUK6Ge5IXu7wnGxLLWINpu2FJBwHyKRX1BLZwk6ebOvd0N/kd/NfoqzvB/lf43hHZhvSCL4sQ9vyFzxF0xHNDJN1fa/8sjfJQ0fEcJQLnT08BoJQQ3gs69qDuKgyVwVt4lYep/1QLFCBbpeeRwnP6SPhwS4bhRnNZF1rMdOnEeM8H7IYn9FuvcitPQaD0P6/SBfG9VFKbXhCZo/4UeE+zKcdHSPdJgwJRgEBNM/g0JoFT+r00fgF6wRr8oFnfhI1sVPkR9+0Y43pQS1JK6XjoE2GRwZQxlKUbq1BmAMKZMebK9odnUWb2d/0Sm28LSkmp+EpcYU50FXlfM8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: b4w
    type: kubernetes.io/dockerconfigjson
