---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: b4w
spec:
  encryptedData:
    .dockerconfigjson: AgBKJvp3zbYKErTvxKbvKKwk2h7Nf6UWtbOhPQJWDasYu6/lZ+5FxwMB5o4oGCOojueJjIG1VrvgS2jqmS91B/ZK0eHszZbsQgdWQHBPGSuKzPQfiI3uX3z+xAdknG5YX7J66Hi/W2t0YxDPtrgdBNzye2EO6TErYCNY7a+JAhxOQSFi9Fm5fYFzkLj7Xf1c14MB7SpOuExgw/u9DFRBwPyY+gQmZhEip6EaNK5M2D9XR1KivJ/ErnY5B+Fit1FnS9625pEcNCoqiTFxtoKN75zBFW4HL+S3WRhGXBNDXwyxiRIL38bDFv65dwQN0V+H3ZpH6P2S4mS+0DpVCFYofLH7h5MfRUMqIZn6WYc9jCZkVpiNaKi4nwQMfgWbJKGw2hITn1VF6IqqcJL79KuNvLx/xFktqex02kdxVXfEz23E2A1J+uQi6txyi0K4AnRYD8CtmmaIrZRTxtkeIJvMJjmvMcHHR64SCXXEnogJHpfTQBn8TUg+ZQqWkg3PVoo6MiuQ+MGT4oi+LJJO2nk7YA6P5HeCDDUUHMXqC/cefnllzqhnUO6KQiYLmDanmIVacr3IOhwN+tEdoB12vy/pSvqWgqdBdCJ5Tu5oHgDW2WCzTAwAQpJq1tWa+J+kthP3HTyVD12txnn5OxurHsYw+/InhncI5y+ReXx6e6YnwTjSlPQpz+p5l3pYbxACIyYgr5q4Sm9CAjsFP9mNJg3Y30X0E8nCAPS7YxczSXuFbVoLFcITiLgdy8yE6L0zoln/1iojCVege6LWd8IxQV1NAu3PWp6bE8MMy3LkLG0g8HqvdPOEGjRsBFPDEVex3NoPP3k0DYj9hZPDkLARt7Qd4Oz6ZMwgX5zHvP8h3ZB0ZTDdKaaWHb9Zitun8thFBPjNQsvmC1ySzuBKNUa5ecLmo+IOyQRs8tU7p/4+XlgNHSC/SSakRvvEBErPJ2O1Ty/0gwSp2AQh9+QW2ZMo5rNwmjtL0vrDzJcIHm5HKS6drF4mKFpC85bgozvIHLrhu+bVxbpGaZK+Whl2f+EfEKCGDlKL37OizJEv8ITuHpDZagS6uk+JRcKYud3yTLSNXiaB/Dg+keucOn2O4fLBAm7cl+WYhiBiOV+Rc+SO/elcavRT+1qIOiuvjsPuIRTtDe5Jqc/IG2EolXCKiYipPPh1Mml7C5pyK43wuXjRvY515CMJ1h/2CAtz355V6zud/gOBYOFwz12GvZo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: b4w
    type: kubernetes.io/dockerconfigjson
