apiVersion: v1
kind: Namespace
metadata:
  name: example

---
# get some persistent storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1M

---
# create a postgres database for the app
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: example
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "s3://cnpg/micro/example"
      endpointURL: https://s3.rileysnyder.dev
      s3Credentials:
        accessKeyId:
          name: minio
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: minio
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip

---
# and schedule a daily backup
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: db
  namespace: example
spec:
  schedule: "0 8 * * * *"
  backupOwnerReference: cluster
  immediate: false
  cluster:
    name: db

---
# run some container in the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
  replicas: 1
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        env:
        - name: EXAMPLE
          value: something
        # add postgres connection details
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: db-app
              key: dbname
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: db-app
              key: username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-app
              key: password
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: db-app
              key: host
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: example

---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
  annotations:
    # add service to tailnet with dns name
    tailscale.com/expose: "true"
    tailscale.com/hostname: "example"
    # add service to local dns via pihole
    external-dns.alpha.kubernetes.io/hostname: example.r.ss
spec:
  # give service a local ip
  type: LoadBalancer
  selector:
    app: example
  ports:
  - name: http
    port: 80
    targetPort: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: example
spec:
  ingressClassName: nginx
  rules:
    # expose to the internet
    - host: example.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  example
                port:
                  number: 80
