apiVersion: v1
kind: Namespace
metadata:
  name: harness-delegate-ng

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harness-delegate-ng
  namespace: harness-delegate-ng
spec:
  repo: https://app.harness.io/storage/harness-download/delegate-helm-chart
  chart: harness-delegate-ng
  targetNamespace: harness-delegate-ng
  valuesContent: |-
    delegateName: lab
    accountId: wlgELJ0TTre5aZhzpt8gVA
    delegateToken: {{ k8s.secrets.harness.delegate_token }}
    managerEndpoint: https://app.harness.io/gratis
    delegateDockerImage: rssnyder/delegate:latest
    replicas: 1
    initScript: |
      microdnf update -y
      microdnf install jq -y
    cpu: 100m
    memory: 1500
