---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: keys
type: Opaque
data:
  username: keys
  password: {{ k8s.secrets.kkeys.postgres.password | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pushover
  namespace: reddit-alerts
type: Opaque
data:
  app: {{ k8s.secrets.reddit_alerts.pushover.app | b64encode }}
  user: {{ k8s.secrets.reddit_alerts.pushover.user | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot
  namespace: discord-bot
type: Opaque
data:
  token: {{ k8s.secrets.discord_bot.token | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: apex-aethir-discord-bot
  namespace: discord-bot
type: Opaque
data:
  token: {{ k8s.secrets.discord_bot.apex_aethir | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-manager
  namespace: discord-bot-manager
type: Opaque
data:
  pgpassword: {{ k8s.secrets.discord_bot_manager.pgpassword | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: survivor-tracker
  namespace: survivor-tracker
type: Opaque
data:
  pgpassword: {{ k8s.secrets.survivor_tracker.pgpassword | b64encode }}
  tautullipassword: {{ k8s.secrets.survivor_tracker.tautullipassword | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: google-sheets-service-account
  namespace: python-functions
type: Opaque
data:
  creds: {{ k8s.secrets.python_functions.google_sheets_service_account_json }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-token
  namespace: dnd-generator
data:
  .dockerconfigjson: {{ k8s.secrets.ghcr_docker_config }}
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: dnd-generator
  namespace: dnd-generator
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.dnd_generator.PG_PASSWORD | b64encode }}
  AWS_SECRET_KEY_ID: {{ k8s.secrets.dnd_generator.AWS_SECRET_KEY_ID | b64encode }}
  AWS_SECRET_ACCESS_KEY: {{ k8s.secrets.dnd_generator.AWS_SECRET_ACCESS_KEY | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: counter
type: Opaque
data:
  PG_PASSWORD: {{ k8s.secrets.counter.PG_PASSWORD | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: pg-admin
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: {{ k8s.secrets.pg_admin.PGADMIN_DEFAULT_PASSWORD | b64encode }}

---
apiVersion: v1
kind: Secret
metadata:
  name: dnd-generator-api
  namespace: pg2s3
type: Opaque
stringData:
  pg2s3.conf: |
    pg_url = "postgresql://dm:{{ k8s.secrets.dnd_generator.PG_PASSWORD }}@192.168.2.2:5432/dndgenerator"
    s3_url = "s3://{{ k8s.secrets.pg2s3.s3.username }}:{{ k8s.secrets.pg2s3.s3.password }}@s3.rileysnyder.dev/pg2s3"
    [backup]
    prefix = "dndgenerator"
    retention = 5
    schedule = "0 0 * * *"
    [restore]
    schemas = ["public"]

---
apiVersion: v1
kind: Secret
metadata:
  name: dst
  namespace: pg2s3
type: Opaque
stringData:
  pg2s3.conf: |
    pg_url = "postgresql://dst_manager:{{ k8s.secrets.discord_bot_manager.pgpassword }}@192.168.2.2:5432/dst"
    s3_url = "s3://{{ k8s.secrets.pg2s3.s3.username }}:{{ k8s.secrets.pg2s3.s3.password }}@s3.rileysnyder.dev/pg2s3"
    [backup]
    prefix = "dst"
    retention = 5
    schedule = "0 0 * * *"
    [restore]
    schemas = ["public"]