apiVersion: v1
kind: Namespace
metadata:
  name: reddit-alerts

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pushover
  namespace: reddit-alerts
spec:
  encryptedData:
    app: AgCy7lyxFPxbNOeKf1BgcifDVkrNWteV/SbFxSMaHcjv0X+J2lDC1SKn0VtCgwDx/9pkCrRKj6IZJjfAQITShFxBDoPvmpjA/mw+/5/PhFDUgq6+OxgCPJvrnKrh9GU/uIpyS9HbkGHHNuED7e4N6cdot8EXYGuIkL3f1n4Vd/ro6eKvVnJDI7WA6ke0ijTkn6SHHsZpZQ0HFFJrBXim4ZyYxXf1icLfEctCPRY6ZlFe+L6wcmsexflLRe5ylgbClm5sMKnNM5SVvoIRXqxwUys6n8VRHBClrutFruez6DvJiviJI48lmkA96FYynj3/1N+G5ogHAluzcVvNII8Dy+g88iLju1SfwXEj/lg+QKQsqK02bqdccAgvukvjTgXYwlYFIXx50NhQeu6d1wCp5+hoXGWYxyFg4gb71yfHKz8WSoBNHW4ElRnWVjlMA/zhurO+8MTAA+Zo37Y8yJEt4aVasXPFzOB64qBIC2Rv2lBUME0cgBkg9jPXliFyF6Gp9v+ACAgDe712UhwYctYsht0BpGUk57L+vO8qdaGrep9gm/bPfidrPGCNAQ4hQlPGze/SEUunD2l2qRupOA02pjzpeOlyUraShhbMViUoy5wTLZI/FWhPN4Clkc2rdTrqDG57oS5m8rnLMUIH+VEJBzgukqmV1dAL5zXhrQlQhYpQLUd49Q2OSY1Wu3A/4gkqh2faf6MkHR9DoX/C+dYEkS066SN1jxZR7bA6SZyx2+wS
    user: AgBHwVeeIqGAQREFEy8cUfTXjmWP9Sg9huQopkii3caxSwqltaSQDbEIxM1MMe8l6GMw4hJd6jo3qWkl0qI1qoU2vRHaVRhqoCRRG5gdHMJNj83DLQlBGViq2muNdg7H6QJyPmqhwAdZMpREZyG8wYJdWv/fbOAYIBJX3lLZT/CwTzeYYoqFoZkkmN1SL27jr4kAGZIRcTUHjKUPcl+6FlbuESFp2X7MpZMJoojaqNcbhq6JXo4dggRJMPeBzQhSrupK87PkVDk8QM4HmwWCzmmMLmOMKY/TLCjX1tM/ZmRO8fkPN8jd/e8ySkMRXI3l4xBDV4qJI4WhjdjMf1Gd2QN7oiEb9FDXAPR5GZ6bwSfRsOsXPn5pcow/BtAL/Bvm7c3YI5i3Wk//Pxx79GErypCpubUhJ/FHuuGtKCSoNrJ6n7r1QYBtwHLTgF5DkJKqUlyWqF3fLFE/3YXMCr1zDskEJwyRTU3FDKbfmpVJDPMvybaiFm6RKlkJ/MaXLPVqevlU8VLwOS9B7e0Tjr7D5e1ycgx5S3h74AsX1kyZmtEznCQizKImoWrAZLYWbaGq7W79Bu/bLeTF6RlcgE3S+U64PA4IHAwJ300r6cDz5P7QEu226PPNKG1AHjuh18JIniBgoeeoVr6um/jPmSGSEKz1wvP82n3Wgq1+ADaOY7HnZpSy5p7bcgIbWPC27durcH99Yzp+dmpAKEniF9YEivXjV9KwjWwGzOCi/O2uxR2g
  template:
    metadata:
      name: pushover
      namespace: reddit-alerts
    type: Opaque

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reddit-alerts
  namespace: reddit-alerts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500M