apiVersion: v1
kind: Namespace
metadata:
  name: example

---
# get some persistance storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1M

---
# run some container in the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
  replicas: 1
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        env:
        - name: EXAMPLE
          value: something
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: example

---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
  annotations:
    # add service to tailnet with dns name
    tailscale.com/expose: "true"
    tailscale.com/hostname: "oc-example"
spec:
  type: ClusterIP
  selector:
    app: example
  ports:
  - name: http
    port: 8080
    targetPort: web

