---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgA43QcX925VDto8iVhOfFFJJ2pnTkm5Xzq18IunprktLf/fyAi2djRvgdDKpOdFP461gZ8yb19IGehflxs0N1NkgpXb0SEeUnvCOxd1GIVj2YhMmLu3RNooak7cuHpKQE1jNuNHv3Dkb5VQ8R3q/nof2/wbFTbUdIeJOPwHEikgKwkQ6vpslLOGNpDb7hb+teOyNAEkI1Xoj6V06eRXvHHYkPdPzYo/U1pnYFsN8uoCkKdUk/NR7oCdbCHQm/Zf6ONYT7O4b1W7qrAM/mbSB+zLltPr6uYhlL8roX26w7J/rVHNi3JvMXPYxIoqzCDMPGWvcN6tBx+7wSVjoWJNi5oxP2+AlYbCk4REz8dCCPyKqGmDYmOFXAGIEtjjZwSVM6MGQxRfwV7OKdiH82a/r8rBCgFTk9czsLB32C3tZ1K2vF0tLTgeJ3FapV4jsMaHzJSd82dAMk8dXTjkUKn/PrSvGmKdiKRgYrMXvfurN1e4NhHvygx4Eeijpqz6j3uqfDNa5DTtRiYCZ+OEh+ABWe1zIkhR6vk/OjInabwPTNsHzxuto+RLe69Jz5fqxNeIKBEXwT7w5fv6XEz+kk/8x4QfsMjrqLOuAQxDolMpSj3b1uOsSald2poCMw+zf8ky9F8mBv145K9fnCu0ZV0o0GDTbP24B9lRZ+I20erTU9Vz0t/s7Kd82LRsqZhuBztDvAm6XL2N0ipDXA==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAdZhzkEWqUMn8amKcSutLtnbUcpeQX0G/0oQkIyr7ZHtUC2KfUEpu6vzt1sNOKRB0BTAWC3WzU+e0eudESt/LyjnQP2wdyfY0rP50t9FA5dnG//ANmkxoDWhTHLMukLWpgY5wZE+otk3CzPsGZIeWC4xILwNm8WFYrhAgnfsL9T7Eqw7BZ+Ygfx7liffCPrb+7aQC2rxZ/MoO5o1uLpt1x/AsLDtJPfqEpHH9INs0B6Xs0YtPXq8P6EToJQD/F4xzujwXC2PoAOthtmcQhiIXCEgSHXiAxSdk//k4wQ37BmsLfCvZthZ4VheYAWoB/X9HoBZTaMgsXmKI8NRXf5QIV0Mfc1QUOooDBhSJAnNrzJ4nmqTV8nj7irN489c7GIopRBRjkUpNVI/DAOwdqS/DaOAZhAs2BJYjPkx7P+tEr5peYcG02TRM3Aw9KaAG1ot6hj9qwVFZ9tZZieZtWaIxpKUUDM83cNwng7UsMMk1trtfZenq60ZbDsBO6tc+tJY5zYCmmTvRARx4SjCShMfnIXNvysBfFKqEqvlcQAZRnBVLDonIPu2BFPXnLsyp92fDMfrSMyklWGOVCt9xbKjdIshwrDgET4MLdJ2VlBwvf6aV6yM/i7zg22bf6br591BUVxGlGvWDugbWGZZk5r0I3GOJuJPXlwDF/8ii8uBMfHt886fjjH1eKrs/Os/FmApFnim+qD7Qox4k=
    AWS_ENDPOINTS: AgA2/xHnwOdhd8Kre8Kxn1XVWTpVGLx4ckmik9WhTpnmQMSC2uLUH+r90xWi4CQO18TpiUpMKmqanvLsjLCYtEtqiK4b/HsbvSvtummjXbqTGHGI5/zGQYUPNfQLJ6CB/AbcpRrqCSLciQ0azDjIgN6AdjW1C2ubsYutcyGk0FWBS4WcIExEjSiu4EiWmyv1HPmxz+4E9rPvQ84M7gcAPvkgmpDwXZayXXiSkQtU7x1HNmozjw+M1nRx8cZLrKknbXF35/etP35fV9JmrDYWaDzxExu6YSPFSjch2x8FebQIpvJ5dIhjvFZOtodVl56edZ0PObZClEqRgisumXRPDcpcOUIH/wsghYVrOMk/WpGwJWH4ZPVd6xv67CjMglqNfg5zO71pwYeUeoYxLyjY6amZDzN5ncmLzxNYjvtfMpWIWXuTbDiY9Kx+hDEL+rutStywU3M2ym1rkTdhpnDBj63gtOd2CzhJGfPZqbFyZYYKf0O4dRuBc/WST+dGDSp63sFZNo3cZr9PxYFqy1GD22D0HlMoMb1iV+QGye/eC+mf+W+XDM1BEYJ9eRFPr2UpzQQkOUjfDHvvxCQZPalbSqTIgTSsBhz4eErfZO+5M9QQOjTv2t9RA8Iemidha5qeEr47ojQFK+m5VsKyYl06JuP1XIRMs+0F33N7DpqInT7z6EC8Q0ykqPo4DJE42uVaVKOcM39bS7V2ptIp2bXh0YSU19s0I30keMLLKw==
    AWS_SECRET_ACCESS_KEY: AgCnRtiW0Us9ZSosxIqFDCDtwr0N7U6U9rK9AW7apjxMG6hSB8iekh2+tC0SpxpqiSDGxjwRPSecSu+2kXQ0NRgt0/HKEeJPI5eaVtiqJ+R52ene10EqdxLzBkKdzvLr3L+GCoCsNNAispHRy0F8id38pLkzVQioZjPYLahN5mKOm+OZlReL9FVCoxUU5t9UBl/ZTIihcfWw7LV54lD803R04iJfERTzIvxCIoAJTYabKXcJIJXPg+URcGx8eZOqDnuDd9l7Rnws5efWifEqoK8QcXzk2t2sVYx5aV32qsqPFimyus7P8Jr0t6JZoGZBsul+9VfzeVvtLcTuuGplBPlyCL4I0KkpabFf9x9IpyniqrB51SJLesMsqGBYpzjG54YoHZSjZr9Pp0iXBLvBWxGGu4MwRf7dUz+TGFjMs1IMH9G9QjBIaGOXPuJoHBEI3pHpXnSKqWmmuiOl5aYcMloOnKRIwiRK8EW6B5g2fLY/t8mfn+M8SAxHBmbtrl9lvDHMX4AKdTW1mp/f94oNriulASLADs4BnsMd0I7gf99NPh7wwxk5mVBrm3gjtMaYZ9EhxdjTvq36HvUUWBNSuRgd6bfnhkg363Da9FT3PmBxhaYaXH/hpsgTVTmnZhI7tx7X4UPcr1JxOORWRHXDAxuWY7V7JhPqtwbDoWMfT+HHPjY1TUPBHfsY15VwlXCc+pK+yUMBvEOfwUUWozMkepqGoybj38CMnq/36xTjyBAk9JmGbqCTPfS9
  template:
    metadata:
      name: minio
      namespace: longhorn-system
    type: Opaque
