---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBFTQXmWJH5M+Cj3FlInI1k3Y/ZSSgr4sHnww3GbHqlpweH0URuVrGqSUxcpdugJe9GPD6T5RLwBy8wfWhL0AJcpA1vZ8048xC9o9ddaAmCbRnbVGgckopeLl5ygyF9/bQQ4UcpwrzYVwzfo/RuDnc+G+d59lqJ+pH/YRpqyfr6dtNthBB8/RyHXQRyhRyPYXAxFESy5z67DfA9WiG6FR70n9fNoQCgoMQiglagi9XURc+ZsktnQUK8Hk6mS1W0rqe54bQ0KkVbGeZxdREeWt8BGxz2P2VZCs0lw01lra65RScc99JQa0Ie+Th1LVk9u5F6ONiC/xpQ83X/0JGlqysQ7GcnTvM7hDdn440/PVaIYvYpdY9iheXKT6obmJflEZjyi49rvz+KfCywrb/yWNrx9ua7UypiZqDN05lPqJJ4KWqru8iX8IW1SYAfdfyTbq5asungtXwNUzFC4m3XJ9dWhYXk2IeKkcd1cj4lS3tY7AnW5ur6hk22Oej1u0k6yN45eLzfVFPKbrUQgYWkVccDUPap0m4DOr4GuhR21zKs8PrtLqNIYuCF5J5RCzFUnWVADoSZGCc1Vv/CiNYwDN9D8XHEAMBPJp/p8TK2oVD+BgiWUMTKVSkLfnnnoGJ8w6z09cn5YITovAt32ixx/yQ37QWVpeZdFqRcJs3fX88zKeu6DWE+9srWwNBfetew0lEKoEyR0erCfA==
  template:
    metadata:
      name: pihole
      namespace: kube-system
    type: Opaque
