---
version: "3"
services:

{{ alloy_compose | to_nice_yaml(indent=2) | indent(2, first=True) }}

  grafana:
    image: grafana/grafana-oss:11.6.4
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: "https://metrics.rileysnyder.dev"
      GF_AUTH_GOOGLE_ENABLED: "true"
      GF_AUTH_GOOGLE_CLIENT_ID: "${GF_AUTH_GOOGLE_CLIENT_ID}"
      GF_AUTH_GOOGLE_CLIENT_SECRET: "${GF_AUTH_GOOGLE_CLIENT_SECRET}"
      GF_AUTH_GOOGLE_SCOPES: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
      GF_AUTH_GOOGLE_AUTH_URL: "https://accounts.google.com/o/oauth2/auth"
      GF_AUTH_GOOGLE_TOKEN_URL: "https://accounts.google.com/o/oauth2/token"
      GF_AUTH_GOOGLE_ALLOWED_DOMAINS: "rileysnyder.dev gmail.com"
    volumes:
      - $APPDATA/grafana:/var/lib/grafana

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio
    network_mode: host
    restart: unless-stopped
    volumes:
      - $APPDATA/minio:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    command: server /data --console-address ":9001"
  
  versitygw:
    image: versity/versitygw:latest
    container_name: versitygw
    hostname: versitygw
    ports:
      - "${S3_PORT}:9002" # API S3
      - "${S3_CONSOLE_PORT}:9003" # Console S3
      - "${S3_ADMIN_PORT}:9004" # API admin S3
    environment:
      - ROOT_ACCESS_KEY=${MINIO_USER}
      - ROOT_SECRET_KEY=${MINIO_PASSWORD}

      - VGW_PORT=:9002
      - VGW_WEBUI_PORT=:9003      # <--- Console 
      - VGW_ADMIN_PORT=:9004      # <--- API admin

      # Identity and Access Management (IAM)
      # The gateway can support multi-tenant mode using an IAM service. The default is to operate in single tenant mode (root account only).
      - VGW_IAM_DIR=/var/lib/versitygw

      # To activate GUI console with admin menus (admin menus will only appear if a IAM is set)
      - VGW_WEBUI_GATEWAYS=http://hurley.corvus-salmon.ts.net:${S3_PORT}
      - VGW_WEBUI_ADMIN_GATEWAYS=http://hurley.corvus-salmon.ts.net:${S3_ADMIN_PORT}

      # To authorize API calls from console
      - VGW_CORS_ALLOW_ORIGIN=http://hurley.corvus-salmon.ts.net:${S3_CONSOLE_PORT}
      - VGW_CORS_ALLOW_HEADER=Authorization,X-Amz-Date,X-Amz-Content-Sha256,Content-Type,X-Amz-User-Agent,X-Amz-Algorithm,X-Amz-Credential,X-Amz-SignedHeaders,X-Amz-Signature

      - VGW_DEBUG=true
    volumes:
      - ${APPDATA}/versitygw/data:/data
      - ${APPDATA}/versitygw/iam:/var/lib/versitygw # For IAM
    #command: ["posix", "/data"]
    # --nometa to avoid `xattr check failed: xattrs are not supported on this filesystem`
    command: ["posix", "--nometa", "/data"]
    restart: unless-stopped

  pihole:
    image: cbcrowe/pihole-unbound:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    domainname: pihole.local
    ports:
      - 8443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8888:80/tcp
    environment:
      FTLCONF_REPLY_ADDR4: ${FTLCONF_REPLY_ADDR4}
      TZ: America/Chicago
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      WEBTHEME: ${WEBTHEME:-default-light}
      REV_SERVER: ${REV_SERVER:-false}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      DNSMASQ_LISTENING: single
    volumes:
      - $APPDATA/pihole:/etc/pihole:rw
      - $APPDATA/pihole-dnsmasq:/etc/dnsmasq.d:rw

  music:
    build: $APPDATA/music
    container_name: music
    ports:
      - "9876:80"

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - $APPDATA/homer:/www/assets
    ports:
      - 8364:8080

volumes:
  db:
    driver: local
  alloy_data: