---
- name: Backup cornelius
  hosts: cornelius
  become: yes

  tasks:

    - name: backup google drive to bucket
      shell:
        cmd: |
          rclone copy riley: /bucket/backup/drive/
    
    # - name: backup bucket to gdrive
    #   shell:
    #     cmd: rclone copy /bucket/{{ item }}    crypt:bucket/{{ item }}
    #   loop:
    #   - backup
    
    - name: backup bucket to zaius
      shell:
        cmd: rsync -varP /bucket/{{ item }}/ zaius:/pale/bucket/{{ item }}/
      loop:
      - backup
      - media/vhs
      - media/books
      - media/cds
      - media/music
      - media/syndicated
      - media/cc
