---
- name: Install and configure file server
  hosts: cornelius.r.ss
  become: yes
  roles:
    - role: geerlingguy.samba
- name: move files
  hosts: cornelius.r.ss
  become: yes
  tasks:
    - name: copy samba file
      copy: 
        src: "templates/{{ ansible_hostname }}/smb.conf"
        dest: "/etc/samba/smb.conf"
    - name: Restart the nginx service
      ansible.builtin.systemd:
        name: smb
        state: restarted
