---
- name: Docker install
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
        - "{{ ansible_user }}"

- name: Docker deploy
  hosts: all
  become: no
  tasks:
    - name: copy compose file
      copy: 
        src: "templates/{{ ansible_hostname }}/docker-compose.yml"
        dest: "/home/{{ ansible_user }}/docker-compose.yml"
        owner: "{{ ansible_user }}"

    - name: compose up
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}"
        remove_orphans: true