---
- name: copy k3s manifests
  hosts: server
  become: yes

  tasks:

    - name: baseline
      template:
        src: "{{ item }}"
        dest: /var/lib/rancher/k3s/server/manifests/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - ../k8s/baseline/*.yaml
