---
- name: copy k3s manifests
  hosts: all
  become: yes

  tasks:

    - name: prune all images on a daily basis
      cron:
        name: "prune images"
        minute: "0"
        hour: "3"
        job: "crictl rmi --prune"