---
- name: copy k3s manifests
  hosts: server
  become: yes

  tasks:

    - name: prune all images on a daily basis
      cron:
        name: "prune images"
        minute: "0"
        hour: "3"
        job: "crictl rmi --prune"
    
    - name: baseline
      template:
        src: "{{ item }}"
        dest: /var/lib/rancher/k3s/server/manifests/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - ../k8s/baseline/*.yaml
    
    - name: manifests
      template:
        src: "{{ item }}"
        dest: /var/lib/rancher/k3s/server/manifests/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - "../k8s/manifests{{ cluster_context }}/*.yaml"
    