---
- name: copy k3s manifests
  hosts: server
  become: yes
  vars:
    manifest_dir: /var/lib/rancher/k3s/server/manifests
    skip_baseline: []
  tasks:

    - name: prune all images on a daily basis
      cron:
        name: "prune images"
        minute: "0"
        hour: "3"
        job: "crictl rmi --prune"
    
    - name: baseline
      template:
        src: "{{ item }}"
        dest: "{{ manifest_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
      with_fileglob:
        - ../k8s/baseline/*.yaml
      when: (item | basename | regex_replace('\.j2$', '')) not in skip_baseline
    
    - name: manifests
      template:
        src: "{{ item }}"
        dest: "{{ manifest_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
      with_fileglob:
        - "../k8s/manifests/{{ cluster_context }}/*.yaml"
    
