---
- name: nix config
  hosts:
  - ben.r.ss
  - baelor.r.ss
  become: yes
  tasks:

    - name: baseline
      template:
        src: "{{ item }}"
        dest: /etc/nixos/{{ item | basename | regex_replace('\.j2$', '') }}
        owner: root
        group: root
      with_fileglob:
        - "templates/{{ ansible_hostname }}/*.nix"

    - name: frigate directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /var/lib/frigate
        - /var/lib/frigate/media
      when: ansible_hostname == 'ben'

    - name: frigate config
      template:
        src: templates/ben/frigate-config.yml.j2
        dest: /var/lib/frigate/config.yml
        owner: root
        group: root
        mode: '0644'
      when: ansible_hostname == 'ben'

    - name: test
      shell: nixos-rebuild test
    
    - name: switch
      shell: nixos-rebuild switch
