---
- name: nix config
  hosts: t480-0,plex
  become: yes
  tasks:

    - name: baseline
      template:
        src: "{{ item }}"
        dest: /etc/nixos/{{ item | basename | regex_replace('\.j2$', '') }}
        owner: root
        group: root
      with_fileglob:
        - "templates/{{ ansible_hostname }}/*.nix"

    - name: rebuild
      shell: nixos-rebuild test
