services:
  hermes:
    build: ./hermes
    image: hermes-agent-calibre:latest
    restart: unless-stopped
    command: gateway run
    ports:
      - "8642:8642"
      - "9119:9119"
    environment:
      HERMES_UID: 1001
      HERMES_GID: 1001
      DISCORD_ALLOW_ALL_USERS: true
      HRMS_ALLOW_CREATE: "1"
      # HERMES_DASHBOARD: 1
    volumes:
      - ~/.hermes:/opt/data
      - /mnt/mass/media/books:/media/books