k3s_cluster:
  children:
    server:
      hosts:
        oca4:
    agent:
      hosts:
        oca5:
        oca6:
        oca7:
  vars:
    ansible_user: ubuntu
    k3s_version: v1.31.0+k3s1
    cluster_context: oc2
    extra_server_args: "--cluster-cidr=10.48.0.0/16 --service-cidr=10.49.0.0/16 --cluster-dns=10.49.0.10 --cluster-domain=oc2.local"
    # extra_agent_args: "--cluster-cidr=10.45.0.0/16"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_enp0s3']['ipv4']['address'] | default(groups['server'][0]) }}"