k3s_cluster:
  children:
    server:
      hosts:
        oca8:
    agent:
      hosts:
        oca9:
  vars:
    ansible_user: ubuntu
    k3s_version: v1.31.0+k3s1
    cluster_context: ocdr
    extra_server_args: "--cluster-cidr=10.45.0.0/16"
    # extra_agent_args: "--cluster-cidr=10.45.0.0/16"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_enp0s3']['ipv4']['address'] | default(groups['server'][0]) }}"