apiVersion: v1
kind: Namespace
metadata:
  name: immich

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: immich
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAb94/YIPu9tRH0IjDznNbQFfqECdqTLyvToWk3rlKtUa8rsAXOmbSrbnznw0My3WUJoOqVNpymXmDObFzC+yOtJ7LuSd8K/Z2oz6ZfTxBjs2SFNl9vRJr2OYHssfDxiPrkhxuUMZNO7GRMe/VaP+oOqW5XfeR5s4F4nOfRrpTNkrZokwM4FGSc18V9XUAMPIlUaAjcQTHaGiFKiQ4Ws2EZlMGilcmSfSk6oFC3N5d47g/vQfOhA2h5b41lsH3FC1IBnRTDIVs2LkQE2Qy+mKALoE/ffycnUXsoIeoMOKaEUrASJes3D/vrXHAJYt+hOo1+k9rYBtWbtirlrlRsF+XTAdxcEjejE+Dj+hah/d0fnwgPYUWHTuTOR+KAjR+XatsbrFm+XlrftdtBbv05n7EEfXojohE1bWiE5+TUI1OYjlPlNr7qjnvfTa4sd3785Z0Uw32iWFODGW1dgDIQd+QxjT6scyGuo1LsavSJVilCgk6FI2qJs5DijXMnBzGupTGOrPA2/NkuWK0rlqWsVSVqK3yg69/1VwUSKC3NGtefENISf2wk0jHNd8JQ+7DJCo84j19h01G9m2P2ts082LnLOdsXtvA2wzAC2nsoGs+vewVWty67IRfjDdBkTlQvFjbdKAmHkLldmwtyzgiUlbM1Eg3pbLhew/IwRtExcZU/zXHbAKzvMywh1NiElXLXFu7sn2Sx47dQPHSwyyc4A9C1GNGtUA==
    AWS_SECRET_ACCESS_KEY: AgCNQ8rBKJbKwkM+iPCcaC1HR5K3alxn9RXIX6D9aCuzVwxZ9fdBPcNjHSEoqFagY84YGb1pSBOZqrObqgl5w6OS0Q1a3jTMPnTCkpB67JDQzkRbcUC6/FLUiLzgPV3VY6IaV2lhH3X/PDyDp7vWtNZoe6lFVfLvnG6nNrfiTlf3/ApGeBlZiSYNZ6EbMMzpCcdE5CQnhAFHWfTfk/3wA9Wp65gok1Qo+sjz8LU1trUaePvf0EDDuzQtRiPwsVNdnmgM/R7/AeJWtj/c4J8ZSZt9hN2p4dZWmfcjzIUtcQugytm3DpJD4mUO6QTixmN0nl8Q7eGr03f01dJQZ2Vn3cYfoWJDE7rpDyr6cmKPF+ZzHs/R8nM8HLfPxz6UJzJzsK3JLKF1COyLW1hC+toCRNjfv2Fzuk2IzdI2J02LC9kamAecz+c43xn458oYhy57rlRM7WWBckU24WZBBpSvJXN+oh5kfHbu0w9+9IYCNDIxfmB4zHzU/EepE04QskliL42bbWb3//TVrp9GuTRWzQvE8MB8Pk8d5SqmYUaPV4wyqQ2QBvjaN2Y3A9yErTyfy0x1/X6Qfc1szXk34wo+NTzX16Zx0qsHy91wrTDInA1BMqd2b55lKd0sU1fUcSF3oL9zwndC4YC7jL1FjxeHMjlm3OmbKlU6WQF2IKJL41hVoqYgbpA1ObXSPjUOHam9Wspbdx5corgfp0L3FY6GvPj5RcHBzrVyYk9F2pgYDvQEa1KCp3JpusBa

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5G

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:15-v0.3.0
  instances: 1
  enableSuperuserAccess: true
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      owner: app
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://cnpg/immich-new"
      endpointURL: https://s3.rileysnyder.dev
      s3Credentials:
        accessKeyId:
          name: minio
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: minio
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip

# for recovery

  bootstrap:
    recovery:
      source: db

  externalClusters:
    - name: db
      barmanObjectStore:
        destinationPath: "s3://cnpg/immich"
        endpointURL: https://s3.rileysnyder.dev
        s3Credentials:
          accessKeyId:
            name: minio
            key: AWS_ACCESS_KEY_ID
          secretAccessKey:
            name: minio
            key: AWS_SECRET_ACCESS_KEY

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: db-hourly
  namespace: immich
spec:
  schedule: "0 0 * * * *"
  backupOwnerReference: cluster
  immediate: true
  cluster:
    name: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
      - name: zira
        nfs:
          server: 192.168.2.6
          path: /scratch/immich
      containers:
      - name: server
        image: ghcr.io/immich-app/immich-server:release
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOSTNAME
          value: redis.redis.svc.cluster.local
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-superuser
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-superuser
              key: password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: db-superuser
              key: host
        ports:
        - name: http
          containerPort: 2283
        volumeMounts:
        - name: zira
          mountPath: /usr/src/app/upload

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: immich
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-learning
  template:
    metadata:
      labels:
        app: machine-learning
    spec:
      containers:
      - name: machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:release
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 3003
        volumeMounts:
        - name: cache
          mountPath: /cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache

---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  type: LoadBalancer
  selector:
    app: machine-learning
  ports:
  - name: api
    port: 3003
    targetPort: api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
spec:
  ingressClassName: nginx
  rules:
    - host: immich.k8s.rileysnyder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  http
                port:
                  number: 80
