services:

  postgres:
    image: postgres:18
    restart: always
    shm_size: 128mb
    environment:
     - POSTGRES_USER=forgejo
     - POSTGRES_PASSWORD=forgejo
     - POSTGRES_DB=forgejo
    volumes: 
      - ./postgres:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432
    networks:
      - forgejo

  server:
    image: codeberg.org/forgejo/forgejo:15
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=postgres:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__service__DISABLE_REGISTRATION=true
    restart: always
    networks:
      - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
    depends_on:
      - postgres

networks:
  forgejo:
    external: false