apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  url: https://cloudnative-pg.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.2"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 5m
  releaseName: cloudnative-pg
